name: deepectransformer
channels:
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - boost=1.74.0=py37h796e4cb_5
  - boost-cpp=1.74.0=h359cf19_6
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - diamond=2.0.11=hdcc8f71_0
  - icu=69.1=h9c3ff4c_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.21.5=py37ha15fc14_3
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.7=h191fe78_0_cpython
  - python_abi=3.7=4_cp37m
  - readline=7.0=h7b6447c_5
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - bio==1.6.2
      - biopython==1.81
      - biothings-client==0.3.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cycler==0.11.0
      - dataclasses==0.6
      - filelock==3.12.2
      - fonttools==4.38.0
      - future==1.0.0
      - gprofiler-official==1.0.0
      - idna==3.10
      - importlib-metadata==6.7.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - mygene==3.2.2
      - numpy==1.21.6
      - packaging==24.0
      - pandas==1.1.5
      - pillow==9.5.0
      - platformdirs==4.0.0
      - pooch==1.8.2
      - protobuf==3.19.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - regex==2024.4.16
      - requests==2.31.0
      - sacremoses==0.0.53
      - sentencepiece==0.1.91
      - tokenizers==0.9.3
      - torch==1.7.0
      - tqdm==4.67.1
      - transformers==3.5.1
      - typing-extensions==4.7.1
      - urllib3==1.26.15
      - zipp==3.15.0

