name: AlphaGEM
channels:
  - gurobi
  - bioconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aria2=1.37.0=hbc8128a_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2024.9.24=h06a4308_0
  - diamond=2.1.10=h43eeafb_2
  - foldseek=9.427df8a=pl5321hb365157_1
  - gawk=5.3.1=hcd3d067_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=hac33072_2
  - gurobi=11.0.3=py310_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.47.0=hadc24fc_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h064dc61_0
  - libzlib=1.3.1=hb9d3cd8_2
  - mpfr=4.2.1=h90cbb55_3
  - ncurses=6.5=he02047a_1
  - openssl=3.4.0=hb9d3cd8_0
  - perl=5.32.1=7_hd590300_perl5
  - python=3.10.15=h4a871b0_2_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.47.0=h9eae976_1
  - tk=8.6.13=noxft_h4845f30_101
  - wget=1.21.4=hda4d442_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - appdirs==1.4.4
      - asttokens==2.4.1
      - attrs==24.2.0
      - biopython==1.84
      - biotite==0.41.2
      - brotli==1.1.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - cloudpathlib==0.20.0
      - cobra==0.29.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - decorator==5.1.1
      - depinfo==2.2.0
      - diskcache==5.6.3
      - einops==0.8.0
      - esm==3.0.8
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fair-esm==2.0.0
      - filelock==3.16.1
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - future==1.0.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.26.3
      - idna==3.10
      - importlib-resources==6.4.5
      - ipython==8.29.0
      - isodate==0.7.2
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - levenshtein==0.26.1
      - logzero==1.7.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgpack-numpy==0.4.8
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openpyxl==3.1.5
      - optlang==1.8.2
      - orthofinder==3.0.1b1
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - pip==24.3.1
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-libsbml==5.20.4
      - pytz==2024.2
      - pyyaml==6.0.2
      - rapidfuzz==3.10.1
      - rdflib==7.1.1
      - rdkit==2024.3.6
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentencepiece==0.2.0
      - six==1.16.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - swiglpk==5.0.12
      - sympy==1.13.1
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.5.1
      - torchtext==0.18.0
      - torchvision==0.20.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
